# Generated by Django 4.2.7 on 2026-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubproposal',
            name='activities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clubproposal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clubproposal',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clubproposal',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clubproposal',
            name='president_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
