# Generated by Django 4.2.7 on 2026-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_clubproposal_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
