# Generated by Django 4.2.7 on 2026-02-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_clubproposal_status_alter_eventproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubproposal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='proposal_attachments/'),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='proposal_attachments/'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
