# Generated by Django 4.2.7 on 2026-03-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_add_event_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubproposal',
            name='advisor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='president_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='president_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
