# Generated by Django 4.2.7 on 2026-03-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_update_status_workflow'),
        ('proposals', '0007_clubproposal_advisor_phone_clubproposal_end_date_and_more'),
    ]

    operations = [
    ]
