# Generated by Django 4.2.7 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_merge_20260307_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubproposal',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
