# Generated by Django 4.2.7 on 2026-04-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_clubproposal_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubproposal',
            name='github',
            field=models.CharField(blank=True, help_text='club-username', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='instagram',
            field=models.CharField(blank=True, help_text='@clubname', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Club LinkedIn', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='meeting_location',
            field=models.CharField(blank=True, help_text='e.g., Tech Building, Room 301', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='meeting_time',
            field=models.CharField(blank=True, help_text='e.g., Every Wednesday at 6:00 PM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubproposal',
            name='member_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of member email addresses'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='agenda_description',
            field=models.TextField(blank=True, help_text='Describe the agenda, schedule and activities', null=True),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='agenda_pdf',
            field=models.FileField(blank=True, help_text='PDF files only, max 10MB', null=True, upload_to='event_agendas/'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='event_poster',
            field=models.ImageField(blank=True, help_text='1200x800px recommended', null=True, upload_to='event_posters/'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Event start time', null=True),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='event_type',
            field=models.CharField(blank=True, help_text='e.g., Academic, Sports, Social', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements for attendees', null=True),
        ),
        migrations.AlterField(
            model_name='clubproposal',
            name='club_logo',
            field=models.ImageField(blank=True, help_text='500x500px recommended', null=True, upload_to='club_logos/'),
        ),
    ]
