# Generated by Django 4.2.7 on 2026-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_clubproposal_github_clubproposal_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventproposal',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='platform_fee_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='platform_fees/'),
        ),
        migrations.AlterField(
            model_name='eventproposal',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('returned_for_revision', 'Returned for Revision')], default='pending_review', max_length=30),
        ),
    ]
