# Generated by Django 4.2.7 on 2026-02-22 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('data_type', models.CharField(default='string', max_length=20)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'db_table': 'ai_configuration',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('advice_feedback', 'Advice Feedback'), ('user_correction', 'User Correction'), ('successful_example', 'Successful Example'), ('failure_case', 'Failure Case')], max_length=30)),
                ('input_text', models.TextField()),
                ('expected_output', models.TextField()),
                ('actual_output', models.TextField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('used_for_training', models.BooleanField(default=False)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Training Data',
                'verbose_name_plural': 'AI Training Data',
                'db_table': 'ai_training_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['data_type'], name='ai_training_data_ty_398554_idx'), models.Index(fields=['is_verified'], name='ai_training_is_veri_957da8_idx'), models.Index(fields=['used_for_training'], name='ai_training_used_fo_71df86_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('text_generation', 'Text Generation'), ('classification', 'Classification'), ('sentiment_analysis', 'Sentiment Analysis'), ('content_analysis', 'Content Analysis')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('training', 'Training'), ('deprecated', 'Deprecated')], default='inactive', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('training_data', models.TextField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeBase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('knowledge_type', models.CharField(choices=[('policy', 'Policy'), ('guideline', 'Guideline'), ('example', 'Example'), ('template', 'Template'), ('faq', 'FAQ')], max_length=20)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Knowledge Base',
                'verbose_name_plural': 'AI Knowledge Base',
                'db_table': 'ai_knowledge_base',
                'ordering': ['-priority', 'title'],
                'indexes': [models.Index(fields=['knowledge_type', 'category'], name='ai_knowledg_knowled_43f2c5_idx'), models.Index(fields=['is_active'], name='ai_knowledg_is_acti_714852_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('advice_request', 'Advice Request'), ('content_analysis', 'Content Analysis'), ('auto_suggestion', 'Auto Suggestion'), ('error_correction', 'Error Correction')], max_length=30)),
                ('input_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='ai_advisor.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interaction',
                'verbose_name_plural': 'AI Interactions',
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='ai_interact_user_id_b9dec6_idx'), models.Index(fields=['created_at'], name='ai_interact_created_52310f_idx'), models.Index(fields=['session_id'], name='ai_interact_session_83afb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAdvice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advice_type', models.CharField(choices=[('event_proposal', 'Event Proposal'), ('club_proposal', 'Club Proposal'), ('content_improvement', 'Content Improvement'), ('policy_compliance', 'Policy Compliance'), ('budget_optimization', 'Budget Optimization')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('target_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_advices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Advice',
                'verbose_name_plural': 'AI Advices',
                'db_table': 'ai_advices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'advice_type'], name='ai_advices_user_id_60783d_idx'), models.Index(fields=['status'], name='ai_advices_status_a57947_idx'), models.Index(fields=['created_at'], name='ai_advices_created_fe4349_idx')],
            },
        ),
    ]
