# Generated by Django 4.2.7 on 2026-03-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0001_initial'),
    ]

    operations = [
        # Index on JSON fields not supported by MySQL in this way
        # MySQL requires generated columns for JSON field indexing
    ]
