# Generated by Django 4.2.7 on 2026-06-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0002_aiknowledgebase_ai_knowledg_tags_c7e0df_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiknowledgebase',
            index=models.Index(fields=['tags'], name='ai_knowledg_tags_c7e0df_idx'),
        ),
    ]
