# Generated by Django 4.2.7 on 2026-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('returned_for_revision', 'Returned for Revision'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=30),
        ),
    ]
