# Generated by Django 5.2 on 2026-05-17 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The specific user (organizer/admin) who approved or rejected the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='approved_by_role',
            field=models.CharField(blank=True, choices=[('organizer', 'Organizer'), ('admin', 'Admin')], help_text='Whether payment was approved/rejected by organizer or admin', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='transaction_info',
            field=models.TextField(blank=True, help_text='Transaction details provided by user (bank ref, amount, date, etc.)', null=True),
        ),
    ]
