# Generated by Django 4.2.7 on 2026-05-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_transaction_info_and_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='reminder_1day_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='reminder_2day_sent',
            field=models.BooleanField(default=False),
        ),
    ]
