# Generated by Django 4.2.7 on 2026-02-14 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('gallery_type', models.CharField(choices=[('event', 'Event'), ('club', 'Club'), ('general', 'General'), ('achievement', 'Achievement'), ('campus', 'Campus Life')], max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery_covers/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_galleries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='events.event')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to='gallery_media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery_thumbnails/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='gallery.gallery')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_media', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.mediafile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gallery.mediacomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Comment',
                'verbose_name_plural': 'Media Comments',
                'db_table': 'media_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_collections', to=settings.AUTH_USER_MODEL)),
                ('media_files', models.ManyToManyField(blank=True, related_name='collections', to='gallery.mediafile')),
            ],
            options={
                'verbose_name': 'Media Collection',
                'verbose_name_plural': 'Media Collections',
                'db_table': 'media_collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_position', models.FloatField(help_text='X position as percentage (0-100)')),
                ('y_position', models.FloatField(help_text='Y position as percentage (0-100)')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='gallery.mediafile')),
                ('tagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('tagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Tag',
                'verbose_name_plural': 'Media Tags',
                'db_table': 'media_tags',
                'indexes': [models.Index(fields=['media_file', 'tagged_user'], name='media_tags_media_f_59ece1_idx'), models.Index(fields=['tagged_user'], name='media_tags_tagged__ffa19c_idx')],
                'unique_together': {('media_file', 'tagged_user')},
            },
        ),
        migrations.CreateModel(
            name='MediaReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('copyright', 'Copyright Violation'), ('violence', 'Violence'), ('privacy', 'Privacy Violation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gallery.mediafile')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Report',
                'verbose_name_plural': 'Media Reports',
                'db_table': 'media_reports',
                'ordering': ['-created_at'],
                'unique_together': {('media_file', 'reported_by')},
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.mediafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Like',
                'verbose_name_plural': 'Media Likes',
                'db_table': 'media_likes',
                'indexes': [models.Index(fields=['media_file', 'user'], name='media_likes_media_f_15584c_idx')],
                'unique_together': {('media_file', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['gallery', 'status'], name='media_files_gallery_fde2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type'], name='media_files_media_t_efc472_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='media_files_uploade_8ca4da_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['created_at'], name='media_files_created_c209ba_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacomment',
            index=models.Index(fields=['media_file', 'is_approved'], name='media_comme_media_f_33e4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacomment',
            index=models.Index(fields=['user'], name='media_comme_user_id_e4cf10_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacomment',
            index=models.Index(fields=['parent'], name='media_comme_parent__d197ec_idx'),
        ),
    ]
