# Generated by Django 4.2.7 on 2026-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album_and_update_mediafile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediafile',
            name='media_files_album_idx',
        ),
    ]
