# Generated by Django 4.2.7 on 2026-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned_for_revision', 'Returned for Revision'), ('active', 'Active'), ('inactive', 'Inactive'), ('published', 'Published')], default='pending', max_length=30),
        ),
    ]
