# Generated by Django 4.2.7 on 2026-03-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('inactive', 'Inactive'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
