from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from .models import (
    SystemOverview, AdminActivity, SystemReport, SystemSetting,
    SystemAlert, SystemBackup, SystemMaintenance, Proposal, ProposalComment
)


@admin.register(SystemOverview)
class SystemOverviewAdmin(admin.ModelAdmin):
    """
    System overview admin interface.
    """
    list_display = ['last_updated']
    readonly_fields = ['id', 'last_updated']
    
    def has_add_permission(self, request):
        return False
    
    def has_change_permission(self, request, obj=None):
        return False


@admin.register(AdminActivity)
class AdminActivityAdmin(admin.ModelAdmin):
    """
    Admin activity admin interface.
    """
    list_display = ['admin', 'action_type', 'description', 'target_object_type', 'created_at']
    list_filter = ['action_type', 'created_at']
    search_fields = ['admin__email', 'description', 'target_object_type']
    readonly_fields = ['id', 'admin', 'created_at']
    ordering = ['-created_at']
    
    def has_add_permission(self, request):
        return False
    
    def has_change_permission(self, request, obj=None):
        return False


@admin.register(SystemReport)
class SystemReportAdmin(admin.ModelAdmin):
    """
    System report admin interface.
    """
    list_display = ['title', 'report_type', 'status', 'generated_by', 'created_at']
    list_filter = ['report_type', 'status', 'created_at']
    search_fields = ['title', 'description', 'generated_by__email']
    readonly_fields = ['id', 'file_path', 'file_size', 'generated_by', 'generated_at', 'created_at']
    ordering = ['-created_at']
    
    fieldsets = (
        (_('Report Info'), {
            'fields': ('report_type', 'title', 'description', 'status')
        }),
        (_('Parameters'), {
            'fields': ('parameters',)
        }),
        (_('File Info'), {
            'fields': ('file_path', 'file_size')
        }),
        (_('Schedule'), {
            'fields': ('generated_at', 'expires_at')
        }),
        (_('Generated By'), {
            'fields': ('generated_by',)
        }),
        (_('Timestamps'), {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )


@admin.register(Proposal)
class ProposalAdmin(admin.ModelAdmin):
    """
    Proposal admin interface for managing club and event proposals.
    """
    list_display = [
        'title', 'type', 'status', 'priority', 'submitted_by', 
        'submitted_at', 'deadline', 'budget_display'
    ]
    list_filter = [
        'type', 'status', 'priority', 'created_at', 'submitted_at'
    ]
    search_fields = [
        'title', 'description', 'submitted_by__email', 'submitted_by__first_name', 'submitted_by__last_name'
    ]
    readonly_fields = ['id', 'submitted_at', 'updated_at']
    ordering = ['-created_at']
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('title', 'description', 'type', 'status', 'priority')
        }),
        ('Details', {
            'fields': ('budget', 'deadline', 'tags')
        }),
        ('Submission', {
            'fields': ('submitted_by',)
        }),
        ('Review', {
            'fields': ('reviewed_by', 'reviewed_at', 'review_comments')
        }),
        ('Timestamps', {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )
    
    def budget_display(self, obj):
        if obj.budget:
            return f"${obj.budget:,.2f}"
        return "No budget"
    budget_display.short_description = 'Budget'
    
    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if request.user.is_superuser:
            return qs
        return qs.filter(status__in=['pending', 'under_review'])


@admin.register(ProposalComment)
class ProposalCommentAdmin(admin.ModelAdmin):
    """
    Proposal comment admin interface.
    """
    list_display = ['proposal', 'author', 'content_short', 'is_internal', 'created_at']
    list_filter = ['is_internal', 'created_at']
    search_fields = ['proposal__title', 'author__email', 'content']
    readonly_fields = ['id', 'created_at', 'updated_at']
    ordering = ['-created_at']
    
    def content_short(self, obj):
        return obj.content[:50] + '...' if len(obj.content) > 50 else obj.content
    content_short.short_description = 'Content'


@admin.register(SystemSetting)
class SystemSettingAdmin(admin.ModelAdmin):
    """
    System setting admin interface.
    """
    list_display = ['key', 'value', 'setting_type', 'category', 'is_public', 'updated_at']
    list_filter = ['setting_type', 'category', 'is_public', 'updated_at']
    search_fields = ['key', 'description']
    ordering = ['category', 'key']
    
    fieldsets = (
        (_('Setting Info'), {
            'fields': ('key', 'value', 'setting_type', 'description')
        }),
        (_('Visibility'), {
            'fields': ('is_public', 'category')
        }),
        (_('Updated By'), {
            'fields': ('updated_by',)
        }),
        (_('Timestamps'), {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )


@admin.register(Proposal)
class ProposalAdmin(admin.ModelAdmin):
    """
    Proposal admin interface for managing club and event proposals.
    """
    list_display = [
        'title', 'type', 'status', 'priority', 'submitted_by', 
        'submitted_at', 'deadline', 'budget_display'
    ]
    list_filter = [
        'type', 'status', 'priority', 'created_at', 'submitted_at'
    ]
    search_fields = [
        'title', 'description', 'submitted_by__email', 'submitted_by__first_name', 'submitted_by__last_name'
    ]
    readonly_fields = ['id', 'submitted_at', 'updated_at']
    ordering = ['-created_at']
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('title', 'description', 'type', 'status', 'priority')
        }),
        ('Details', {
            'fields': ('budget', 'deadline', 'tags')
        }),
        ('Submission', {
            'fields': ('submitted_by',)
        }),
        ('Review', {
            'fields': ('reviewed_by', 'reviewed_at', 'review_comments')
        }),
        ('Timestamps', {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )
    
    def budget_display(self, obj):
        if obj.budget:
            return f"${obj.budget:,.2f}"
        return "No budget"
    budget_display.short_description = 'Budget'
    
    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if request.user.is_superuser:
            return qs
        return qs.filter(status__in=['pending', 'under_review'])


@admin.register(ProposalComment)
class ProposalCommentAdmin(admin.ModelAdmin):
    """
    Proposal comment admin interface.
    """
    list_display = ['proposal', 'author', 'content_short', 'is_internal', 'created_at']
    list_filter = ['is_internal', 'created_at']
    search_fields = ['proposal__title', 'author__email', 'content']
    readonly_fields = ['id', 'created_at', 'updated_at']
    ordering = ['-created_at']
    
    def content_short(self, obj):
        return obj.content[:50] + '...' if len(obj.content) > 50 else obj.content
    content_short.short_description = 'Content'


@admin.register(SystemAlert)
class SystemAlertAdmin(admin.ModelAdmin):
    """
    System alert admin interface.
    """
    list_display = ['title', 'alert_type', 'status', 'source', 'created_at']
    list_filter = ['alert_type', 'status', 'source', 'created_at']
    search_fields = ['title', 'message', 'source']
    readonly_fields = ['id', 'created_at']
    ordering = ['-created_at']
    
    fieldsets = (
        (_('Alert Info'), {
            'fields': ('title', 'message', 'alert_type', 'status', 'source')
        }),
        (_('Metadata'), {
            'fields': ('metadata',)
        }),
        (_('Resolution'), {
            'fields': ('acknowledged_by', 'acknowledged_at', 'resolved_by', 'resolved_at')
        }),
        (_('Schedule'), {
            'fields': ('expires_at',)
        }),
        (_('Timestamps'), {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )


@admin.register(Proposal)
class ProposalAdmin(admin.ModelAdmin):
    """
    Proposal admin interface for managing club and event proposals.
    """
    list_display = [
        'title', 'type', 'status', 'priority', 'submitted_by', 
        'submitted_at', 'deadline', 'budget_display'
    ]
    list_filter = [
        'type', 'status', 'priority', 'created_at', 'submitted_at'
    ]
    search_fields = [
        'title', 'description', 'submitted_by__email', 'submitted_by__first_name', 'submitted_by__last_name'
    ]
    readonly_fields = ['id', 'submitted_at', 'updated_at']
    ordering = ['-created_at']
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('title', 'description', 'type', 'status', 'priority')
        }),
        ('Details', {
            'fields': ('budget', 'deadline', 'tags')
        }),
        ('Submission', {
            'fields': ('submitted_by',)
        }),
        ('Review', {
            'fields': ('reviewed_by', 'reviewed_at', 'review_comments')
        }),
        ('Timestamps', {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )
    
    def budget_display(self, obj):
        if obj.budget:
            return f"${obj.budget:,.2f}"
        return "No budget"
    budget_display.short_description = 'Budget'
    
    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if request.user.is_superuser:
            return qs
        return qs.filter(status__in=['pending', 'under_review'])


@admin.register(ProposalComment)
class ProposalCommentAdmin(admin.ModelAdmin):
    """
    Proposal comment admin interface.
    """
    list_display = ['proposal', 'author', 'content_short', 'is_internal', 'created_at']
    list_filter = ['is_internal', 'created_at']
    search_fields = ['proposal__title', 'author__email', 'content']
    readonly_fields = ['id', 'created_at', 'updated_at']
    ordering = ['-created_at']
    
    def content_short(self, obj):
        return obj.content[:50] + '...' if len(obj.content) > 50 else obj.content
    content_short.short_description = 'Content'


@admin.register(SystemBackup)
class SystemBackupAdmin(admin.ModelAdmin):
    """
    System backup admin interface.
    """
    list_display = ['backup_type', 'status', 'file_size', 'initiated_by', 'created_at']
    list_filter = ['backup_type', 'status', 'created_at']
    search_fields = ['initiated_by__email']
    readonly_fields = ['id', 'file_path', 'file_size', 'compression_ratio', 'started_at', 'completed_at', 'initiated_by', 'created_at']
    ordering = ['-created_at']
    
    fieldsets = (
        (_('Backup Info'), {
            'fields': ('backup_type', 'status')
        }),
        (_('File Info'), {
            'fields': ('file_path', 'file_size', 'compression_ratio')
        }),
        (_('Schedule'), {
            'fields': ('started_at', 'completed_at')
        }),
        (_('Initiated By'), {
            'fields': ('initiated_by',)
        }),
        (_('Error Info'), {
            'fields': ('error_message',)
        }),
        (_('Metadata'), {
            'fields': ('metadata',)
        }),
        (_('Timestamps'), {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )


@admin.register(Proposal)
class ProposalAdmin(admin.ModelAdmin):
    """
    Proposal admin interface for managing club and event proposals.
    """
    list_display = [
        'title', 'type', 'status', 'priority', 'submitted_by', 
        'submitted_at', 'deadline', 'budget_display'
    ]
    list_filter = [
        'type', 'status', 'priority', 'created_at', 'submitted_at'
    ]
    search_fields = [
        'title', 'description', 'submitted_by__email', 'submitted_by__first_name', 'submitted_by__last_name'
    ]
    readonly_fields = ['id', 'submitted_at', 'updated_at']
    ordering = ['-created_at']
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('title', 'description', 'type', 'status', 'priority')
        }),
        ('Details', {
            'fields': ('budget', 'deadline', 'tags')
        }),
        ('Submission', {
            'fields': ('submitted_by',)
        }),
        ('Review', {
            'fields': ('reviewed_by', 'reviewed_at', 'review_comments')
        }),
        ('Timestamps', {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )
    
    def budget_display(self, obj):
        if obj.budget:
            return f"${obj.budget:,.2f}"
        return "No budget"
    budget_display.short_description = 'Budget'
    
    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if request.user.is_superuser:
            return qs
        return qs.filter(status__in=['pending', 'under_review'])


@admin.register(ProposalComment)
class ProposalCommentAdmin(admin.ModelAdmin):
    """
    Proposal comment admin interface.
    """
    list_display = ['proposal', 'author', 'content_short', 'is_internal', 'created_at']
    list_filter = ['is_internal', 'created_at']
    search_fields = ['proposal__title', 'author__email', 'content']
    readonly_fields = ['id', 'created_at', 'updated_at']
    ordering = ['-created_at']
    
    def content_short(self, obj):
        return obj.content[:50] + '...' if len(obj.content) > 50 else obj.content
    content_short.short_description = 'Content'


@admin.register(SystemMaintenance)
class SystemMaintenanceAdmin(admin.ModelAdmin):
    """
    System maintenance admin interface.
    """
    list_display = ['title', 'maintenance_type', 'status', 'scheduled_start', 'scheduled_end']
    list_filter = ['maintenance_type', 'status', 'scheduled_start']
    search_fields = ['title', 'description']
    readonly_fields = ['id', 'actual_start', 'actual_end', 'notification_sent', 'initiated_by', 'created_at']
    ordering = ['-scheduled_start']
    
    fieldsets = (
        (_('Maintenance Info'), {
            'fields': ('title', 'description', 'maintenance_type', 'status')
        }),
        (_('Schedule'), {
            'fields': ('scheduled_start', 'scheduled_end', 'actual_start', 'actual_end')
        }),
        (_('Services'), {
            'fields': ('affected_services', 'notification_sent')
        }),
        (_('Initiated By'), {
            'fields': ('initiated_by',)
        }),
        (_('Timestamps'), {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )


@admin.register(Proposal)
class ProposalAdmin(admin.ModelAdmin):
    """
    Proposal admin interface for managing club and event proposals.
    """
    list_display = [
        'title', 'type', 'status', 'priority', 'submitted_by', 
        'submitted_at', 'deadline', 'budget_display'
    ]
    list_filter = [
        'type', 'status', 'priority', 'created_at', 'submitted_at'
    ]
    search_fields = [
        'title', 'description', 'submitted_by__email', 'submitted_by__first_name', 'submitted_by__last_name'
    ]
    readonly_fields = ['id', 'submitted_at', 'updated_at']
    ordering = ['-created_at']
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('title', 'description', 'type', 'status', 'priority')
        }),
        ('Details', {
            'fields': ('budget', 'deadline', 'tags')
        }),
        ('Submission', {
            'fields': ('submitted_by',)
        }),
        ('Review', {
            'fields': ('reviewed_by', 'reviewed_at', 'review_comments')
        }),
        ('Timestamps', {
            'fields': ('id', 'created_at', 'updated_at')
        }),
    )
    
    def budget_display(self, obj):
        if obj.budget:
            return f"${obj.budget:,.2f}"
        return "No budget"
    budget_display.short_description = 'Budget'
    
    def get_queryset(self, request):
        qs = super().get_queryset(request)
        if request.user.is_superuser:
            return qs
        return qs.filter(status__in=['pending', 'under_review'])


@admin.register(ProposalComment)
class ProposalCommentAdmin(admin.ModelAdmin):
    """
    Proposal comment admin interface.
    """
    list_display = ['proposal', 'author', 'content_short', 'is_internal', 'created_at']
    list_filter = ['is_internal', 'created_at']
    search_fields = ['proposal__title', 'author__email', 'content']
    readonly_fields = ['id', 'created_at', 'updated_at']
    ordering = ['-created_at']
    
    def content_short(self, obj):
        return obj.content[:50] + '...' if len(obj.content) > 50 else obj.content
    content_short.short_description = 'Content'
